### PR TITLE
apply jupyter-igv Browser to multiple lines/datatypes on depmap 

### PR DESCRIPTION
**Pull request by javadnoorb**
This code creates multiple IGV tracks for the same cell line (or multiple) for quick checks. It currently only works in Jupyter Notebook.

Example code:

```Python
from gsheets import Sheets

sample_tracker = 'https://docs.google.com/spreadsheets/d/1Pgb5fIClGnErEqzxpU7qqX6ULpGTDjvzWwDN8XUJKIY'
sheets_obj = Sheets.from_files('~/.client_secret.json', '~/.storage.json')

sheets = sheets_obj.get(sample_tracker).sheets
depmap_samples = sheets[0].to_frame(header=0, index_col=0)

cols = ['arxspan_id', 'datatype', 'internal_bam_filepath', 'internal_bai_filepath',
        'legacy_bam_filepath', 'legacy_bai_filepath', 'stripped_cell_line_name']

depmap_sample1 = depmap_samples[depmap_samples['arxspan_id'] == 'ACH-000090'][cols]
depmap_sample2 = depmap_samples[depmap_samples['arxspan_id'] == 'ACH-002184'][cols]

from depmapomics.helper import depmap_igv
locus = '11:62296943'
# locus = '7:55242466' # EGFR
b = depmap_igv({"genome": "hg19", 'locus':locus})

#[['internal_bam_filepath', 'legacy_bam_filepath']]
schemas1 = [
    {'datatype': 'wes', 'iloc_value': 0, 'column_type':'legacy'}, 
    {'datatype': 'wgs', 'iloc_value': 0, 'column_type':'legacy'}, 
#     {'datatype': 'RRBS', 'iloc_value': 0, 'column_type':'internal'}, 
#     {'datatype': 'raindance', 'iloc_value': 0, 'column_type':'internal'}, 
    {'datatype': 'hybrid_capture', 'iloc_value': 0, 'column_type':'internal'},
    {'datatype': 'rna', 'iloc_value': 0, 'column_type':'legacy'}
]
schemas2 = [
    {'datatype': 'wes', 'iloc_value': 0, 'column_type':'legacy'}, 
#     {'datatype': 'wgs', 'iloc_value': 0, 'column_type':'legacy'}, 
#     {'datatype': 'RRBS', 'iloc_value': 0, 'column_type':'internal'}, 
#     {'datatype': 'raindance', 'iloc_value': 0, 'column_type':'internal'}, 
#     {'datatype': 'hybrid_capture', 'iloc_value': 0, 'column_type':'internal'}
]

b.get_the_tracks(depmap_sample1, schemas1)
b.get_the_tracks(depmap_sample2, schemas2)
b.show()
```

top part of the output:
image

### CODE REVIEW

**Comment by jkobject** [comment]
it seems very early stage. 
I have a couple questions:
- could we add the ability to add the CN and maf files for those lines as well?
- can we make it more efficient so that it directly and so we can get rid of the first 12 lines?
-

**Comment by javadnoorb** [comment]
- Yes, if that information is in the tracker it would be straightforward to add. 
- The main reason I didn't make this more efficient is because there is a mixture of hg19 and hg38 on the same columns of the tracker. So I had to look at file names to figure out what's inside them.

**Comment by jkobject** [comment]
Ok so that you know. Now legacy is always hg19 and hg38 is internal.

This is true for rna/wes/wgs the rest has never been mapped to hg38 and it's internal_ is hg19

**Comment by javadnoorb** [comment]
ok. I cleaned this up to read from the tracker. Here's the new example:

```python
from depmapomics.helper import depmap_igv
b = depmap_igv({"genome": "hg19", 'locus':'11:62296943'})
b.get_the_tracks(['ACH-000090', 'ACH-002184'], ['wes', 'wgs', 'RRBS', 'rna'])
b.show()
```

**Comment by jkobject** [comment]
I am not able to make it work yet. I will try to find if I can debug it when I get time

**Comment by javadnoorb** [comment]
@jkobject  I used to get this when the token wasn't set up properly. I wonder if this is an issue with the code that I've written or your Jupyter IGV. Can you get jupyter igv examples directly working?

https://github.com/igvteam/igv-jupyter

**Comment by jkobject** [comment]
yes it works

**Comment by jkobject** [comment]
I am using python 3.7.3, notebook  6.0.1,  igv 0.9.6, igv-jupyter 0.9.7

**Comment by javadnoorb** [comment]
this is weird. can you check if this `b.depmap_samples_subset` has anything in it?

**Pull request merged**
